// metrics/collectors/svelte/svelte-material-ui/demo/App.svelte
<script>
	import Button from '@smui/button';
	import Textfield from '@smui/textfield';
	import Switch from '@smui/switch';

	window.setVisibleComponent = (componentName, isVisible) => {
		visible[componentName] = isVisible;
	};
	window.availableComponents = ['Button', 'Input', 'Switch'];

	let visible = {
		Button: false,
		Switch: false,
		Input: false,
	};
</script>

{#if visible.Button}
	<Button>Content</Button>
{/if}
{#if visible.Switch}
	<Switch />
{/if}
{#if visible.Input}
	<Textfield label="Label" />
{/if}

// metrics/collectors/react/material-ui/demo/App.tsx
import React from 'react';
import ReactDOM from 'react-dom';

import { Button, TextField, Switch } from '@material-ui/core';

import {
	ComponentVisibilitySetterWindow,
	BaseComponent,
} from '../../../shared/shapes';

declare const window: ComponentVisibilitySetterWindow;

window.availableComponents = ['Button', 'Input', 'Switch'];

const App = () => {
	const [
		visibleComponent,
		setVisibleComponent,
	] = React.useState<BaseComponent | null>(null);

	window.setVisibleComponent = (componentName, isVisible) => {
		if (!isVisible) {
			setVisibleComponent(null);
		} else {
			setVisibleComponent(componentName);
		}
	};

	return (
		<>
			{visibleComponent === 'Button' && <Button>Content</Button>}
			{visibleComponent === 'Input' && <TextField />}
			{visibleComponent === 'Switch' && <Switch />}
		</>
	);
};

ReactDOM.render(<App />, document.getElementById('root'));
