// metrics/collectors/multi-framework/onsen-react/demo/App.tsx
import React from 'react';
import ReactDOM from 'react-dom';

import { Button, Input, Switch } from 'react-onsenui';

import {
	ComponentVisibilitySetterWindow,
	BaseComponent,
} from '../../../shared/shapes';

declare const window: ComponentVisibilitySetterWindow;

window.availableComponents = ['Button', 'Input', 'Switch'];

const App = () => {
	const [
		visibleComponent,
		setVisibleComponent,
	] = React.useState<BaseComponent | null>(null);
	const [numberOfComponents, setNumberOfComponents] = React.useState<
		unknown[]
	>([]);

	window.setVisibleComponent = (
		componentName,
		numberOfComponents: number,
		isVisible
	) => {
		if (!isVisible) {
			setVisibleComponent(null);
		} else {
			setVisibleComponent(componentName);
		}
		setNumberOfComponents(new Array(numberOfComponents).fill(''));
	};

	return (
		<>
			{visibleComponent === 'Button' &&
				numberOfComponents.map(() => <Button>Content</Button>)}
			{visibleComponent === 'Input' &&
				numberOfComponents.map(() => (
					<Input placeholder="placeholder" />
				))}
			{visibleComponent === 'Switch' &&
				numberOfComponents.map(() => <Switch />)}
		</>
	);
};

ReactDOM.render(<App />, document.getElementById('root'));

// metrics/collectors/svelte/svelte-material-ui/demo/App.svelte
<script>
	import Button from '@smui/button';
	import Textfield from '@smui/textfield';
	import Switch from '@smui/switch';

	window.setVisibleComponent = (componentName, numberOfComponents, isVisible) => {
		visible[componentName] = new Array(numberOfComponents).fill('');
	};
	window.availableComponents = ['Button', 'Input', 'Switch'];

	let visible = {
		Button: false,
		Switch: false,
		Input: false,
	};
</script>

{#if visible.Button.length}
	{#each visible.Button as btn, i }
		<Button>Content</Button>
	{/each}
{/if}
{#if visible.Switch.length}
	{#each visible.Switch as btn, i }
		<Switch />
	{/each}
{/if}
{#if visible.Input.length}
	{#each visible.Input as btn, i }
		<Textfield label="Label" />
	{/each}
{/if}
