// metrics/collectors/react/react-bootstrap/demo/App.tsx
import React from 'react';
import ReactDOM from 'react-dom';

import { Button, Form } from 'react-bootstrap';

import {
	ComponentVisibilitySetterWindow,
	BaseComponent,
} from '../../../shared/shapes';

declare const window: ComponentVisibilitySetterWindow;

window.availableComponents = ['Button', 'Input', 'Switch'];

const App = () => {
	const [
		visibleComponent,
		setVisibleComponent,
	] = React.useState<BaseComponent | null>(null);
	const [numberOfComponents, setNumberOfComponents] = React.useState<
		unknown[]
	>([]);

	window.setVisibleComponent = (
		componentName,
		numberOfComponents,
		isVisible
	) => {
		if (!isVisible) {
			setVisibleComponent(null);
		} else {
			setVisibleComponent(componentName);
		}
		setNumberOfComponents(new Array(numberOfComponents).fill(''));
	};

	return (
		<>
			{visibleComponent === 'Button' &&
				numberOfComponents.map(() => <Button>Content</Button>)}
			<Form>
				{visibleComponent === 'Input' &&
					numberOfComponents.map(() => <Form.Control type="text" />)}
				{visibleComponent === 'Switch' &&
					numberOfComponents.map(() => (
						<Form.Check type="checkbox" />
					))}
			</Form>
		</>
	);
};

ReactDOM.render(<App />, document.getElementById('root'));

// metrics/collectors/angular/ngx-bootstrap/demo/src/app/app.component.ts
import { ChangeDetectorRef, Component } from '@angular/core';

declare const window: any;

@Component({
	selector: 'app-root',
	templateUrl: './app.component.html',
	styleUrls: ['./app.component.css'],
})
export class AppComponent {
	title = 'demo';

	constructor(private _cd: ChangeDetectorRef) {
		window.availableComponents = [
			'Button',
			'Switch',
			'Input',
		];
		window.setVisibleComponent = (
			componentName: string,
			numberOfComponents: number,
			isVisible: boolean
		) => {
			if (!isVisible) {
				this.visibleComponent = null;
			} else {
				this.visibleComponent = componentName;
			}
			this.componentCount = new Array(numberOfComponents).fill('');
			this._cd.detectChanges();
		};
	}

	public visibleComponent: string | null = null;
	public componentCount: unknown[] = [];
}

<div style="margin: 50px; margin-top: 300px">
	<div *ngFor="let a of componentCount" *ngIf="visibleComponent == 'Button'">
		<button type="button" class="btn btn-primary">Button</button>
	</div>
	<div *ngFor="let a of componentCount" *ngIf="visibleComponent == 'Input'">
		<input class="form-control" />
	</div>
	<div *ngFor="let a of componentCount" *ngIf="visibleComponent == 'Switch'">
		<button
			type="button"
			class="btn btn-primary"
			btnCheckbox
			btnCheckboxTrue="1"
			btnCheckboxFalse="0"
		>
			Checkbox
		</button>
	</div>
</div>
