// metrics/collectors/svelte/svelte-mui/demo/App.svelte
<script>
	import { Button, Checkbox, Textfield } from 'svelte-mui';

	window.setVisibleComponent = (componentName, isVisible) => {
		visible[componentName] = isVisible;
	};
	window.availableComponents = ['Button', 'Input', 'Switch'];

	let visible = {
		Button: false,
		Switch: false,
		Input: false,
	};
</script>

{#if visible.Button}
	<Button>Content</Button>
{/if}
{#if visible.Switch}
	<Checkbox />
{/if}
{#if visible.Input}
	<Textfield />
{/if}

// metrics/collectors/react/semantic-ui-react/demo/App.tsx
import React from 'react';
import ReactDOM from 'react-dom';

import { Button, Input, Checkbox } from 'semantic-ui-react';

import {
	ComponentVisibilitySetterWindow,
	BaseComponent,
} from '../../../shared/shapes';

declare const window: ComponentVisibilitySetterWindow;

window.availableComponents = ['Button', 'Input', 'Switch'];

const App = () => {
	const [
		visibleComponent,
		setVisibleComponent,
	] = React.useState<BaseComponent | null>(null);

	window.setVisibleComponent = (componentName, isVisible) => {
		if (!isVisible) {
			setVisibleComponent(null);
		} else {
			setVisibleComponent(componentName);
		}
	};

	return (
		<>
			{visibleComponent === 'Button' && <Button>Content</Button>}
			{visibleComponent === 'Input' && <Input />}
			{visibleComponent === 'Switch' && <Checkbox />}
		</>
	);
};

ReactDOM.render(<App />, document.getElementById('root'));
